/*
 * complex.java
 *
 * Created on 18 ���������� 2007, 1:07 ��
 */

package gr.demokritos.iit.eleon.ui;

import gr.demokritos.iit.eleon.authoring.Mpiro;
import gr.demokritos.iit.eleon.authoring.QueryHashtable;

import java.util.Enumeration;
import java.util.Properties;
import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author  dbilid
 */
public class Complex extends java.awt.Dialog {
    
    /** Creates new form complex */
    public Complex(java.awt.Frame parent, boolean modal, boolean equiv) {
        super(parent, modal);
        initComponents();
        equival=equiv;
        Enumeration entitytypes= QueryHashtable.getEntityTypesAndEntitiesHashtableFromMainDBHashtable("Entity type").keys();
        Vector entityTypes=new Vector();
        while(entitytypes.hasMoreElements())
        {
            entityTypes.add(entitytypes.nextElement().toString());
        }
        jList1.setListData(entityTypes);
        
        Enumeration Entities= QueryHashtable.getEntityTypesAndEntitiesHashtableFromMainDBHashtable("Entity").keys();
        Vector entities=new Vector();
        while(Entities.hasMoreElements())
        {
            entities.add(Entities.nextElement().toString());
        }
        jList2.setListData(entities);
        Enumeration properties= QueryHashtable.propertiesHashtable.keys();
        Vector prop=new Vector();
        while(properties.hasMoreElements())
        {
            prop.add(properties.nextElement().toString());
        }
        jList3.setListData(prop);
        
        jList4.setModel(expressions);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 170, 210);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2);
        jScrollPane2.setBounds(230, 40, 170, 210);

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });

        jScrollPane3.setViewportView(jList3);

        add(jScrollPane3);
        jScrollPane3.setBounds(450, 40, 170, 210);

        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });

        jScrollPane4.setViewportView(jList4);

        add(jScrollPane4);
        jScrollPane4.setBounds(100, 370, 430, 132);

        jLabel1.setText("Named Classes");
        add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 14);

        jLabel2.setText("Instances");
        add(jLabel2);
        jLabel2.setBounds(230, 20, 130, 14);

        jLabel3.setText("Properties");
        add(jLabel3);
        jLabel3.setBounds(450, 20, 100, 14);

        jButton1.setText("\u2200");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1);
        jButton1.setBounds(570, 260, 50, 20);

        jLabel4.setText("Class Expressions");
        add(jLabel4);
        jLabel4.setBounds(260, 350, 120, 14);

        jButton2.setText("\u2203");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2);
        jButton2.setBounds(510, 260, 50, 20);

        jButton3.setText("\u220D");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        add(jButton3);
        jButton3.setBounds(450, 260, 50, 20);

        add(jTextField1);
        jTextField1.setBounds(540, 320, 70, 20);

        jButton4.setText("\u2264");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        add(jButton4);
        jButton4.setBounds(510, 290, 50, 23);

        jButton5.setText("\u2265");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        add(jButton5);
        jButton5.setBounds(450, 290, 50, 23);

        jButton6.setText("=");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        add(jButton6);
        jButton6.setBounds(570, 290, 50, 23);

        jButton7.setText("Add Enumeration");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        add(jButton7);
        jButton7.setBounds(230, 270, 160, 23);

        jButton8.setText("Add Named Class");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        add(jButton8);
        jButton8.setBounds(20, 270, 150, 23);

        jButton9.setText("\u222A");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        add(jButton9);
        jButton9.setBounds(220, 510, 50, 20);

        jButton10.setText("\u2229");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        add(jButton10);
        jButton10.setBounds(290, 510, 50, 20);

        jButton11.setText("\u00AC");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        add(jButton11);
        jButton11.setBounds(360, 510, 50, 20);

        jButton12.setText("add Selected");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        add(jButton12);
        jButton12.setBounds(260, 550, 110, 23);

        jLabel5.setText("value:");
        add(jLabel5);
        jLabel5.setBounds(500, 320, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ValueChanged
// TODO add your handling code here:
        if(jList3.getSelectedValue()!=null && jList4.getSelectedValue()!=null){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
        }
        else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
        }
        if(jList3.getSelectedValue()!=null && jList2.getSelectedValue()!=null){
            jButton3.setEnabled(true);
            //jButton2.setEnabled(true);
        }
        else{
            jButton3.setEnabled(false);
           // jButton2.setEnabled(false);
        }
        if(jList3.getSelectedValue()!=null){
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
        }
        else{
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
        }
    }//GEN-LAST:event_jList3ValueChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
// TODO add your handling code here:
         if(jList2.getSelectedValue()!=null){
            jButton7.setEnabled(true);
        }
        else{
            jButton7.setEnabled(false);
        }
          if(jList3.getSelectedValue()!=null && jList2.getSelectedValue()!=null){
            jButton3.setEnabled(true);
            //jButton2.setEnabled(true);
        }
        else{
            jButton3.setEnabled(false);
           // jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
// TODO add your handling code here:
        if(jList1.getSelectedValue()!=null){
            jButton8.setEnabled(true);
        }
        else{
            jButton8.setEnabled(false);
        }
        
    }//GEN-LAST:event_jList1ValueChanged

    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
// TODO add your handling code here:
        if(jList4.getSelectedValue()!=null){
            jButton12.setEnabled(true);
            jButton11.setEnabled(true);
        }
        else{
            jButton12.setEnabled(false);
            jButton11.setEnabled(false);
        }
        
        if(jList4.getSelectedValues().length>1){
            jButton10.setEnabled(true);
            jButton9.setEnabled(true);
        }
        else{
            jButton10.setEnabled(false);
            jButton9.setEnabled(false);
        }
        if(jList3.getSelectedValue()!=null && jList4.getSelectedValue()!=null){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
        }
        else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
        }
        
    }//GEN-LAST:event_jList4ValueChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
// TODO add your handling code here:
        
        Equivalent temp=new Equivalent(Mpiro.win.getFrames()[0], true, equival);
         temp.addExpression(jList4.getSelectedValue().toString());
         temp.dispose();
         this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
        try{
                expressions.add(jList4.getModel().getSize(),"( ="+Integer.valueOf(jTextField1.getText())+" Property:"+jList3.getSelectedValue().toString()+")");
        }
        catch(java.lang.NumberFormatException c){
            MessageDialog error=new MessageDialog(this, "INVALID NUMBER");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
        try{
                expressions.add(jList4.getModel().getSize(),"( \u2265"+Integer.valueOf(jTextField1.getText())+" Property:"+jList3.getSelectedValue().toString()+")");
                }
        catch(java.lang.NumberFormatException c){
            MessageDialog error=new MessageDialog(this, "INVALID NUMBER");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        try{
        expressions.add(jList4.getModel().getSize(),"( \u2264"+Integer.valueOf(jTextField1.getText())+" Property:"+jList3.getSelectedValue().toString()+")");
        }
        catch(java.lang.NumberFormatException c){
            MessageDialog error=new MessageDialog(this, "INVALID NUMBER");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
// TODO add your handling code here:
        expressions.add(jList4.getModel().getSize(),"( \u00AC"+jList4.getSelectedValue().toString()+")");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
expressions.add(jList4.getModel().getSize(),"("+jList4.getSelectedValues()[0].toString()+"\u2229"+jList4.getSelectedValues()[1]+")");// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
expressions.add(jList4.getModel().getSize(),"("+jList4.getSelectedValues()[0].toString()+"\u222A"+jList4.getSelectedValues()[1]+")");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
                        expressions.add(jList4.getModel().getSize(),"(\u220D Property:"+ jList3.getSelectedValue().toString()+" Individual:"+jList2.getSelectedValue().toString()+")");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
                expressions.add(jList4.getModel().getSize(),"(\u2203 Property:"+ jList3.getSelectedValue().toString()+" "+jList4.getSelectedValue().toString()+")");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        expressions.add(jList4.getModel().getSize(),"(\u2200 Property:"+ jList3.getSelectedValue().toString()+" "+jList4.getSelectedValue().toString()+")");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
       String enumer="({";
       Object[] instances= jList2.getSelectedValues();
       for(int i=0;i<instances.length;i++){
           if(i>0)
               enumer=enumer+", ";
           enumer=enumer+"Individual:"+instances[i].toString();
       }
       enumer=enumer+"})";
       expressions.add(jList4.getModel().getSize(),enumer);
         
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
        expressions.add(jList4.getModel().getSize(),"(Class:"+jList1.getSelectedValue()+")");
        
    }//GEN-LAST:event_jButton8ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
   
    private  DefaultListModel expressions=new DefaultListModel();
    private boolean equival;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
