/*
 * Datatyype.java
 *
 * Created on 13 ����������� 2007, 1:52 ��
 */

package gr.demokritos.iit.eleon.ui;

import gr.demokritos.iit.eleon.authoring.DataBasePanel;
import gr.demokritos.iit.eleon.authoring.QueryHashtable;

import java.util.Vector;

/**
 *
 * @author  dbilid
 */
public class DatatypeValue extends java.awt.Dialog {
    
    /** Creates new form Datatyype */
    public DatatypeValue(java.awt.Frame parent, boolean modal, String type, String fieldName, String Value) {
        super(parent, modal);
        initComponents();
        //val=new Vector();
      //  Vector cell=new Vector();
        Vector ent=(Vector) QueryHashtable.mainDBHashtable.get(QueryHashtable.nameWithoutOccur(DataBasePanel.last.toString()));
        ent=(Vector) ent.elementAt(0);
        ent=(Vector) ent.elementAt(0);
        if (type.equalsIgnoreCase("number")){
            
            for(int i=3;i<ent.size();i++){
                cell=(Vector) ent.elementAt(i);
                if (cell.elementAt(0).toString().equalsIgnoreCase(fieldName)){
                    break;
                }}
                String[] values= Value.split(" ");
                
                for(int j=0;j<values.length;j++){
                    val.add(values[j]);
                }
                jList1.setListData(val);
                
            
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 210, 110);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1);
        jButton1.setBounds(80, 190, 75, 23);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2);
        jButton2.setBounds(80, 150, 75, 23);

        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(40, 220, 50, 14);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(100, 220, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        val.add(jTextField1.getText());
        cell.setElementAt(val.toString().replaceAll(",","").replace("[","").replace("]",""),1);
        jList1.setListData(val);
       // KDialog addValue = new KDialog("Add value", "value:", "", new Vector(), false, "ADD VALUE");
       // addValue.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

   // public static void addValue(String value){
      //  Vector val=new Vector();
    /*    Vector cell=new Vector();
        Vector ent=(Vector) QueryHashtable.mainDBHashtable.get(QueryHashtable.nameWithoutOccur(DataBasePanel.last.toString()));
        ent=(Vector) ent.elementAt(0);
        ent=(Vector) ent.elementAt(0);
  //      if (type.equalsIgnoreCase("number")){
            
            for(int i=3;i<ent.size();i++){
                cell=(Vector) ent.elementAt(i);
                 cell=(Vector) ent.elementAt(i);
                if (cell.elementAt(0).toString().equalsIgnoreCase("fieldName")){
                    break;
                }}
            */
            
  //      val.add(value);
   //     cell.setElementAt(val.toString().replaceAll(",","").replace("[","").replace("]",""),1);
   //     jList1.setListData(val);
   // }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
     //   Vector val=new Vector();
        //Vector cell=new Vector();
        val.remove(jList1.getSelectedValue());
        cell.setElementAt(val.toString().replaceAll(",","").replace("[","").replace("]",""),1);
        jList1.setListData(val);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
     //   val.clear();
       // cell.clear();
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatatypeValue(new java.awt.Frame(), true, "test", "test", "test").setVisible(true);
            }
        });
    }
    private  Vector val=new Vector();
  //  private static Vector val=new Vector();
    private  Vector cell=new Vector();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
