/*
 * PServerPanel.java
 *
 * Created on 4 ��������� 2007, 1:33 ��
 */

package gr.demokritos.iit.eleon.ui;

import gr.demokritos.iit.eleon.authoring.BackupDB;
import gr.demokritos.iit.eleon.authoring.DataBasePanel;
import gr.demokritos.iit.indigo.adaptation.ParseAndInitialize;
import gr.demokritos.iit.indigo.adaptation.Code_for_Load_Robotic_Personalities.*;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author  dimitris
 */
public class PServerPanel extends javax.swing.JDialog {
    
    /** Creates new form PServerPanel */
    public PServerPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jTextField1.setText("53000");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 50, 60, 20);

        jLabel1.setText("Nav Server IP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 30, 140, 14);

        jLabel2.setText("Nav Server Port");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 130, 14);

        jTextField2.setText("127.0.0.1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 50, 54, 20);

        jLabel3.setText("DB Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 120, 14);

        jTextField3.setText("root");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(40, 110, 50, 20);

        jLabel4.setText("DB Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 90, 120, 14);

        jButton1.setText("Load Data to DB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(90, 160, 140, 23);

        jButton2.setText("Start PServer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(90, 210, 140, 23);

        jPasswordField1.setText("m14531821m");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 110, 76, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
         String file="UserModelling.rdf";
         String fileForRobotics="RobotModelling.rdf";
	    String xeniosPath="jdbc:mysql://localhost/xenios";	    
	    String PerServerPath="jdbc:mysql://localhost/pserver";	
            
            BackupDB b=new BackupDB(jTextField3.getText(),new String(jPasswordField1.getPassword()));
		b.CreateBackups();
            
                String parent="";
                if(new File(jTextField1.getText()).getParent()!=null)
                    parent=new File(jTextField1.getText()).getParent();
             //   m.loadOntologyDataToDB(jTextField1.getText(), jTextField4.getText(), jTextField5.getText(), jTextField3.getText(), new String(jPasswordField1.getPassword()));
        ParseAndInitialize a=new ParseAndInitialize(file,parent, jTextField3.getText(),new String(jPasswordField1.getPassword()),xeniosPath,PerServerPath);
		a.parseConcatenated();
                ParseAndInitializeForRobotPreferences pai=new ParseAndInitializeForRobotPreferences(fileForRobotics,parent, jTextField3.getText(),new String(jPasswordField1.getPassword()),xeniosPath);
                pai.parseConcatenatedForRobotPreferences();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        Runtime runtime = Runtime.getRuntime();
      //  String[] com = new String[2];
//com[0] = "cmd";
//com[1] = "test.bat";
//Process p = Runtime.getRuntime().exec(com);
        try {            
            Process proc = runtime.exec("cmd /c start PServer.bat");
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        DataBasePanel.pServerIsStarted=true;
        DataBasePanel.dbUser=jTextField3.getText();
        DataBasePanel.dbPass=new String(jPasswordField1.getPassword());
        DataBasePanel.navIP=jTextField2.getText();
        DataBasePanel.navPort=Integer.parseInt(jTextField1.getText());
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PServerPanel(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}
