/*
 * reasoner.java
 *
 * Created on 7 ��������� 2006, 4:48 ��
 */

package gr.demokritos.iit.eleon.ui;

import gr.demokritos.iit.eleon.authoring.OwlExport;
import gr.demokritos.iit.eleon.authoring.QueryOptionsHashtable;

import java.io.File;
import jracer.*;
/**
 *
 * @author  dbilid
 */
public class Reasoner extends javax.swing.JDialog {
    
    /** Creates new form reasoner */
    public Reasoner(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        tempOwlFile= new File("OwlTemp.owl");
        String hhhh=tempOwlFile.getAbsolutePath();
        String ggg=tempOwlFile.getAbsolutePath().substring(0,tempOwlFile.getAbsolutePath().indexOf(":\\"))+":\\\\OwlTemp.owl";
        if(tempOwlFile.getAbsolutePath().contains(" ")){
            tempOwlFile=new File(tempOwlFile.getAbsolutePath().substring(0,tempOwlFile.getAbsolutePath().indexOf(":\\"))+":\\\\OwlTemp.owl");
        }
        try{
        OwlExport.ExportToOwlFile(tempOwlFile,"RDF/XML-ABBREV", QueryOptionsHashtable.getBaseURI(),tempOwlFile.getName(),false);
        }
        catch(java.lang.Exception e){}
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(228, 228, 228));
        jButton1.setText("Ask Racer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(60, 150, 100, 23);

        jTextField1.setText("127.0.0.1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 30, 60, 20);

        jTextField2.setText("8088");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 60, 40, 20);

        jTextField3.setText("(check-abox-coherence)");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(60, 90, 160, 20);

        jLabel1.setText("IP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 80, 14);

        jLabel2.setText("Port");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 80, 14);

        jLabel3.setText("Command");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 80, 14);

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 220, 310, 180);

        jLabel4.setText("Result");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 70, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
       // String hhh="file:///"+tempOwlFile.getAbsolutePath().replaceAll("\\\\","/");
         //String ip="127.0.0.1";
        String ip=jTextField1.getText();
    int port=Integer.parseInt(jTextField2.getText());
    String command= jTextField3.getText();
String hhh=tempOwlFile.toURI().toString();
    //    try {            
    //        String ggg=tempOwlFile.toURL().toString();
    //    } catch (MalformedURLException ex) {
     //       ex.printStackTrace();
     //   }
    RacerServer racer1=new RacerServer(ip,port);
    try {
	racer1.openConnection();
	System.out.println(racer1.send("(owl-read-document "+'"'+tempOwlFile.toURI().toString()+'"'+")"));
	jTextPane1.setText(racer1.send(command));
	racer1.closeConnection();
    }
    catch (Exception e) {
	e.printStackTrace();
    }
    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reasoner(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    private File tempOwlFile;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}
