/* Generated By:JavaCC: Do not edit this line. ClassParserConstants.java */
package gr.demokritos.iit.eleon.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ClassParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IND = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int PROP = 7;
  /** RegularExpression Id. */
  int NUM = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IND>",
    "<CLASS>",
    "<PROP>",
    "<NUM>",
    "\"(\"",
    "\"\\u00ac\"",
    "\"\\u2203\"",
    "\"\\u220d\"",
    "\"\\u2200\"",
    "\"\\u2265\"",
    "\"=\"",
    "\"\\u2264\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\")\"",
    "\"\\u222a\"",
    "\"\\u2229\"",
  };

}
